version: "3.8"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 10

  postgres:
    image: postgres:15.0-alpine
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql1/data
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
    healthcheck:
      test: pg_isready --username=user --dbname=db --quiet
      interval: 15s
      timeout: 5s

volumes:
  data: